using System.Text;

namespace PackageGuard.Core.Scaffolding;

/// <summary>
/// Renders the JSON configuration file written by <c>packageguard init</c>: a <c>settings.allow.licenses</c>
/// allow list for the chosen <see cref="SoftwareProfile"/>, an optional <c>warn</c> section for tolerated
/// copyleft licenses, and optional risk gates in the <c>deny</c> section, annotated with comments that explain
/// each part.
/// </summary>
public static class ConfigScaffolder
{
    private const string Indent = "    ";

    /// <summary>
    /// Builds the full contents of the generated configuration file.
    /// </summary>
    /// <param name="profile">The kind of software the configuration is generated for.</param>
    /// <param name="allowedLicenses">The licenses to allow.</param>
    /// <param name="warnLicenses">
    /// Allowed licenses that should still be reported as warnings (typically the tolerated copyleft licenses).
    /// </param>
    /// <param name="includeRiskGates">
    /// Whether to add risk-based <c>deny</c> rules (risk score, OSV severity, deprecation and package age).
    /// </param>
    public static string BuildConfigJson(SoftwareProfile profile, IReadOnlyList<string> allowedLicenses,
        IReadOnlyList<string> warnLicenses, bool includeRiskGates)
    {
        var builder = new StringBuilder();

        builder.AppendLine("{");
        AppendHeaderComment(builder, profile);
        builder.AppendLine($"{Indent}\"settings\": {{");

        List<string> sections = [BuildAllowSection(allowedLicenses)];
        if (warnLicenses.Count > 0)
        {
            sections.Add(BuildWarnSection(warnLicenses));
        }

        if (includeRiskGates)
        {
            sections.Add(BuildRiskGateSection());
        }

        builder.AppendLine(string.Join($",{Environment.NewLine}", sections));

        if (includeRiskGates)
        {
            AppendRiskExceptionsComment(builder);
        }

        builder.AppendLine($"{Indent}}}");
        builder.Append('}');

        return builder.ToString();
    }

    private static void AppendHeaderComment(StringBuilder builder, SoftwareProfile profile)
    {
        string presetName = LicensePresets.GetPresetName(profile);

        builder.AppendLine($"{Indent}// Generated by \"packageguard init\" from the licenses found in this repository.");
        builder.AppendLine($"{Indent}// Preset: {presetName}");
        builder.AppendLine($"{Indent}//");
        builder.AppendLine($"{Indent}// Copyleft licenses require you to share source code under some conditions. Weak");
        builder.AppendLine($"{Indent}// copyleft (e.g. LGPL, MPL) only affects the licensed component itself. Strong");
        builder.AppendLine($"{Indent}// copyleft (e.g. GPL) can require your own code to be released under the same");
        builder.AppendLine($"{Indent}// license. Network copyleft (AGPL) extends that requirement to software offered");
        builder.AppendLine($"{Indent}// as a network service, which matters most for SaaS products.");
        builder.AppendLine($"{Indent}//");
        builder.AppendLine($"{Indent}// Review this list and adjust it to match your policy, then run \"packageguard .\"");
        builder.AppendLine($"{Indent}// to see which packages, if any, violate it. To adopt the policy gradually, add");
        builder.AppendLine($"{Indent}// --treat-deny-as-warning so violations are reported without failing the build.");
    }

    private static string BuildAllowSection(IReadOnlyList<string> allowedLicenses)
    {
        return BuildLicenseSection("allow", allowedLicenses, "Only these licenses are allowed. Everything else is a violation.");
    }

    private static string BuildWarnSection(IReadOnlyList<string> warnLicenses)
    {
        return BuildLicenseSection("warn", warnLicenses,
            "Allowed, but reported as a warning so the copyleft obligations stay visible. Warnings never fail the build.");
    }

    private static string BuildLicenseSection(string name, IReadOnlyList<string> licenses, string comment)
    {
        var builder = new StringBuilder();

        builder.AppendLine($"{Indent}{Indent}// {comment}");
        builder.AppendLine($"{Indent}{Indent}\"{name}\": {{");

        if (licenses.Count == 0)
        {
            builder.AppendLine($"{Indent}{Indent}{Indent}\"licenses\": []");
        }
        else
        {
            builder.AppendLine($"{Indent}{Indent}{Indent}\"licenses\": [");
            builder.AppendLine(string.Join($",{Environment.NewLine}",
                licenses.Select(license => $"{Indent}{Indent}{Indent}{Indent}\"{license}\"")));
            builder.AppendLine($"{Indent}{Indent}{Indent}]");
        }

        builder.Append($"{Indent}{Indent}}}");
        return builder.ToString();
    }

    private static string BuildRiskGateSection()
    {
        string pad = $"{Indent}{Indent}{Indent}";
        var builder = new StringBuilder();

        builder.AppendLine($"{Indent}{Indent}// Risk gates. Setting any of these makes PackageGuard collect risk data on every run,");
        builder.AppendLine($"{Indent}{Indent}// which is slower and works best with a GitHub API key. See the risk metrics docs.");
        builder.AppendLine($"{Indent}{Indent}\"deny\": {{");
        builder.AppendLine($"{pad}// Deny packages in the High risk zone (overall score is 0-100).");
        builder.AppendLine($"{pad}\"maxOverallRisk\": 60,");
        builder.AppendLine($"{pad}// Deny packages whose security risk (0-10) or worst known vulnerability (CVSS) is high.");
        builder.AppendLine($"{pad}\"maxSecurityRisk\": 7,");
        builder.AppendLine($"{pad}\"maxOsvSeverityScore\": 7.0,");
        builder.AppendLine($"{pad}\"denyDeprecated\": true,");
        builder.AppendLine($"{pad}// Deny versions published too recently, a cheap defence against a malicious release.");
        builder.AppendLine($"{pad}\"minPackageAgeDays\": {{ \"npm\": 14, \"nuget\": 3 }}");
        builder.Append($"{Indent}{Indent}}}");

        return builder.ToString();
    }

    private static void AppendRiskExceptionsComment(StringBuilder builder)
    {
        builder.AppendLine();
        builder.AppendLine($"{Indent}{Indent}// To accept the risk of a specific package, add an exception. It only exempts the package");
        builder.AppendLine($"{Indent}{Indent}// from the risk gates above, never from the license rules, and can expire:");
        builder.AppendLine($"{Indent}{Indent}// \"riskExceptions\": [");
        builder.AppendLine($"{Indent}{Indent}//     {{ \"package\": \"SomePackage\", \"reason\": \"Vetted manually\", \"expiresOn\": \"2027-01-01\" }}");
        builder.AppendLine($"{Indent}{Indent}// ]");
    }
}
