using System.Text;

namespace PackageGuard.Core.Init;

/// <summary>
/// Renders the JSON configuration file written by <c>packageguard init</c>: a <c>settings.allow.licenses</c>
/// allow list for the chosen <see cref="SoftwareProfile"/>, annotated with comments that explain the preset
/// and what copyleft means for it.
/// </summary>
public static class InitConfigWriter
{
    /// <summary>
    /// Builds the full contents of the generated configuration file.
    /// </summary>
    public static string BuildConfigJson(SoftwareProfile profile, IReadOnlyList<string> allowedLicenses)
    {
        var builder = new StringBuilder();

        builder.AppendLine("{");
        AppendHeaderComment(builder, profile);
        builder.AppendLine("    \"settings\": {");
        builder.AppendLine("        \"allow\": {");
        AppendLicenses(builder, allowedLicenses);
        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.Append('}');

        return builder.ToString();
    }

    private static void AppendHeaderComment(StringBuilder builder, SoftwareProfile profile)
    {
        string presetName = LicensePresets.GetPresetName(profile);

        builder.AppendLine("    // Generated by \"packageguard init\" from the licenses found in this repository.");
        builder.AppendLine($"    // Preset: {presetName}");
        builder.AppendLine("    //");
        builder.AppendLine("    // Copyleft licenses require you to share source code under some conditions. Weak");
        builder.AppendLine("    // copyleft (e.g. LGPL, MPL) only affects the licensed component itself. Strong");
        builder.AppendLine("    // copyleft (e.g. GPL) can require your own code to be released under the same");
        builder.AppendLine("    // license. Network copyleft (AGPL) extends that requirement to software offered");
        builder.AppendLine("    // as a network service, which matters most for SaaS products.");
        builder.AppendLine("    //");
        builder.AppendLine("    // Review this list and adjust it to match your policy, then run \"packageguard .\"");
        builder.AppendLine("    // to see which packages, if any, violate it.");
    }

    private static void AppendLicenses(StringBuilder builder, IReadOnlyList<string> allowedLicenses)
    {
        if (allowedLicenses.Count == 0)
        {
            builder.AppendLine("            \"licenses\": []");
            return;
        }

        builder.AppendLine("            \"licenses\": [");

        for (int i = 0; i < allowedLicenses.Count; i++)
        {
            string comma = i < allowedLicenses.Count - 1 ? "," : "";
            builder.AppendLine($"                \"{allowedLicenses[i]}\"{comma}");
        }

        builder.AppendLine("            ]");
    }
}
